# Generated by Django 6.0.2 on 2026-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_email_profile_admin_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='user',
            new_name='usuario',
        ),
    ]
