# Generated by Django 6.0.2 on 2026-02-10 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('POL', 'Policia'), ('AMB', 'Ambulancia'), ('BOM', 'Bombero')], default='POL', max_length=3)),
                ('usuario', models.ManyToManyField(related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
