# Generated by Django 6.0.2 on 2026-02-10 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='usuario',
            field=models.ManyToManyField(blank=True, null=True, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
