# Generated by Django 6.0.2 on 2026-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='matricula',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modelo',
            new_name='model',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('POL', 'Policia'), ('AMB', 'Ambulancia'), ('BOM', 'Bombero')], default='POL', max_length=3),
        ),
    ]
