# Generated by Django 6.0.2 on 2026-02-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='usuario',
        ),
    ]
