# Generated by Django 6.0.2 on 2026-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_marca_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='enrollment',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='usuario',
        ),
    ]
