# Generated by Django 6.0.2 on 2026-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(default='vehicle_pictures/nopicture.png', upload_to='vehicle_pictures'),
        ),
    ]
