# Generated by Django 6.0.2 on 2026-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(default='vehicle_pictures/nopicture.svg', upload_to='vehicle_pictures'),
        ),
    ]
