# Generated by Django 6.0.2 on 2026-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='picture',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='imagen',
            field=models.ImageField(default='imagenes_vehiculos/noimagen.svg', upload_to='imagenes_vehiculos'),
        ),
    ]
