# Generated by Django 6.0.2 on 2026-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='imagen',
            field=models.ImageField(default='imagenes_vehiculos/noimagen.svg', upload_to='imagenes_vehiculos'),
        ),
    ]
