# Generated by Django 6.0.2 on 2026-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes_vehiculos/noimagen.svg', null=True, upload_to='imagenes_vehiculos'),
        ),
    ]
