# Generated by Django 6.0.2 on 2026-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkitem',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='checkitem',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='updated_at',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='checkitem',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='vehicle',
            new_name='vehiculo',
        ),
    ]
