# Generated by Django 6.0.2 on 2026-02-10 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='checklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
