# Generated by Django 6.0.2 on 2026-02-10 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_checklist_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='usuario',
            field=models.ManyToManyField(related_name='checklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
