# Generated by Django 6.0.2 on 2026-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_rename_active_checkitem_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=models.ManyToManyField(to='checklists.checkitem'),
        ),
    ]
