# Generated by Django 6.0.2 on 2026-02-10 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_remove_checklist_item_checklist_item'),
        ('vehicles', '0005_alter_vehicle_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='item',
            field=models.ManyToManyField(related_name='checklists', to='checklists.checkitem'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='usuario',
            field=models.ManyToManyField(related_name='checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='vehicles.vehicle'),
        ),
    ]
