# Generated by Django 6.0.2 on 2026-02-11 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklist_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='usuario',
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
