# Generated by Django 6.0.2 on 2026-02-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_checklist_item_alter_checklist_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checklists', to='checklists.checkitem'),
        ),
    ]
